### ISSUE TITLE
给含有单图的说说点赞时出错

### ISSUE THREAD

**Issue by TigerCubDen** [JamzumSum/Qzone2TG#12]
效果为 实际点赞成功，但小红心并没有加在消息的最下面。

错误日志：
```
[INFO] 2021 Aug 22 08:51:18 telegram:   like post start
[ERROR] 2021 Aug 22 08:51:18 telegram.ext.dispatcher:   No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/app/src/tgfrontend/tg.py", line 182, in onButtonClick
    self.like(query)
  File "/app/src/tgfrontend/tg.py", line 203, in like
    text=query.message.text_html + br * 2 + '❤',
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

原因：对单图说说的修改应该使用 `edit_message_caption()` 而不是 `edit_message_text()`，[使用方法](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html?highlight=edit#telegram.Bot.edit_message_caption)。

**Comment by JamzumSum** [comment]
感谢, 会尽快修复

**Comment by JamzumSum** [comment]
请检查[2.0.0b1](https://github.com/JamzumSum/Qzone2TG/releases/tag/2.0.0b1)是否仍存在此问题. (我自己没问题了
#7 的问题由于重写了代码理论上应该不复存在, 如果新增了BUG欢迎issue

**Comment by TigerCubDen** [comment]
> 请检查[2.0.0b1](https://github.com/JamzumSum/Qzone2TG/releases/tag/2.0.0b1)是否仍存在此问题. (我自己没问题了
> #7 的问题由于重写了代码理论上应该不复存在, 如果新增了BUG欢迎issue

![image](https://user-images.githubusercontent.com/55782476/131211799-c0eb0896-34fa-4128-9dde-0d17031f7ddd.png)

它不会自己创建数据库吗？

**Comment by TigerCubDen** [comment]
当解决上面的问题重新运行后，发现总是会永远卡在 `start polling` 上，也没有任何错误信息返回。

![image](https://user-images.githubusercontent.com/55782476/131213558-22c5a59f-4aa7-44ce-96ea-d7dbc355ee72.png)

**Comment by TigerCubDen** [comment]
换成扫码登陆时，报错如下：

![image](https://user-images.githubusercontent.com/55782476/131214417-20972dcd-1e96-4b91-aaa3-661640407ad2.png)

**Comment by TigerCubDen** [comment]
顺带一提：我这里写错了，帮我把 yml 改成 yaml 吧，谢谢啦

![image](https://user-images.githubusercontent.com/55782476/131215038-75c17b09-3ef3-427a-91b2-91ed160ef6ed.png)

**Comment by JamzumSum** [comment]
数据库父目录不存在的情况已经在beta3中处理, beta3将尽快放出.
从beta2开始, run之后默认没有任何动作. 要自动执行start命令, 请将`bot`配置段中的`auto_start`设为`True`. 手动start可以直接发送`/start`给bot. 参考[完整配置说明](https://github.com/JamzumSum/Qzone2TG/wiki/%E9%85%8D%E7%BD%AE%E6%96%87%E6%A1%A3)和[推荐命令列表](https://github.com/JamzumSum/Qzone2TG#telegram-commands)

另, 脚本启动参数中`-c`可以指定配置文件路径.

**Comment by TigerCubDen** [comment]
不知道为什么。我看了数据库，里面的表都是空的，只定义了字段，没有数据写进来

**Comment by TigerCubDen** [comment]
```
[ERROR] 2021 Aug 28 21:14:29 frontend.tg: 【湖北】小钊, 昨天 23:48: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/tiger/Qzone2TG/src/frontend/tg/__init__.py", line 96, in send
    *i.content(),
  File "/home/tiger/Qzone2TG/src/frontend/tg/ui.py", line 254, in content
    return self.msg(), self.img()
  File "/home/tiger/Qzone2TG/src/middleware/__init__.py", line 19, in img
    return self.feed.parseImage()
  File "/home/tiger/Qzone2TG/src/qzone/parser/__init__.py", line 99, in parseImage
    img = [
  File "/home/tiger/Qzone2TG/src/qzone/parser/__init__.py", line 101, in <listcomp>
    re.search(r"trueSrc:'(http.*?)'",
AttributeError: 'NoneType' object has no attribute 'group'
```
以上是未发送成功消息的错误报告

![image](https://user-images.githubusercontent.com/55782476/131219348-5c02ed5a-c2c0-4aec-aa35-a0662e9342ea.png)

另外，每次（自动）刷新它都会重复发送之前未成功的消息😂
