### ISSUE TITLE
failed to parse img-item/img/@onload when parsing image

### ISSUE THREAD

**Issue by JamzumSum** [JamzumSum/Qzone2TG#13]
```
[ERROR] 2021 Aug 28 21:14:29 frontend.tg: 【湖北】小钊, 昨天 23:48: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/tiger/Qzone2TG/src/frontend/tg/__init__.py", line 96, in send
    *i.content(),
  File "/home/tiger/Qzone2TG/src/frontend/tg/ui.py", line 254, in content
    return self.msg(), self.img()
  File "/home/tiger/Qzone2TG/src/middleware/__init__.py", line 19, in img
    return self.feed.parseImage()
  File "/home/tiger/Qzone2TG/src/qzone/parser/__init__.py", line 99, in parseImage
    img = [
  File "/home/tiger/Qzone2TG/src/qzone/parser/__init__.py", line 101, in <listcomp>
    re.search(r"trueSrc:'(http.*?)'",
AttributeError: 'NoneType' object has no attribute 'group'
```
以上是未发送成功消息的错误报告

![image](https://user-images.githubusercontent.com/55782476/131219348-5c02ed5a-c2c0-4aec-aa35-a0662e9342ea.png)

另外，每次（自动）刷新它都会重复发送之前未成功的消息😂

_Originally posted by @TigerCubDen in https://github.com/JamzumSum/Qzone2TG/issues/12#issuecomment-907625764_

**Comment by JamzumSum** [comment]
@TigerCubDen 不知道能否提供导致错误的标签属性? 

将下述循环表达式
https://github.com/JamzumSum/Qzone2TG/blob/53ac652c7522aef4854703b65a6152907db8b9ba/src/qzone/parser/__init__.py#L99-L103
替换为
``` python
img = [
    (src := i.attrib['src']).startswith('http') and src
    or \
    (src := re.search(r"trueSrc:'(http.*?)'", i.attrib['onload'])) and
        src.group(1).replace('\\', '')
    or
    logger.warning('cannot parse @onload: ' + i.attrib['onload'])
    for i in img
]
```
并修改https://github.com/JamzumSum/Qzone2TG/blob/53ac652c7522aef4854703b65a6152907db8b9ba/src/qzone/parser/__init__.py#L104
为
``` python
return [i.replace('rf=0-0', 'rf=viewer_311') for i in img if i]
```

之后运行`/resend`, 以重新触发该错误. 
(若并非正则表达式问题, 后续可能需要您提供该标签的.attrib字段信息)

**Comment by TigerCubDen** [comment]
![image](https://user-images.githubusercontent.com/55782476/131304409-08df3185-0077-4eda-b612-4eaca1197586.png)

无相关错误日志输出

**Comment by TigerCubDen** [comment]
> ![image](https://user-images.githubusercontent.com/55782476/131304409-08df3185-0077-4eda-b612-4eaca1197586.png)
> 
> 无相关错误日志输出

重启 bot 后它将之前发过的动态又全部重新发了一遍，然后报相同的错误

**Comment by TigerCubDen** [comment]
![image](https://user-images.githubusercontent.com/55782476/131306706-741f6007-5091-4f20-b539-00a8ada21baa.png)

**Comment by JamzumSum** [comment]
这似乎是新引入的[错误](https://github.com/JamzumSum/Qzone2TG/commit/41075219036f1b7d087e1d33d16920cb53b8c603#diff-b4b0474a78f06c76608e8f4a52fe6f31c1cd12ffe6bf43bd667bae87676707f1R88).... (`not new` -> `new == False`)

bot每次都会重发未发送的日志, 确实
正常来说, 要重发的只是因为网络错误而非程序错误( 只不过现在bug太多导致重发也没有用

**Comment by TigerCubDen** [comment]
![image](https://user-images.githubusercontent.com/55782476/131312619-3c1f8062-42af-45fc-b5c4-fb0c5c37fca3.png)

这个问题的原因找到了，bot 在群组和频道发送消息的频率被 telegram 限制为20条/分钟，在一对一对话中为30条/秒。

**Comment by TigerCubDen** [comment]
![image](https://user-images.githubusercontent.com/55782476/131322604-39674c26-d0e1-4952-b9a9-f220226b7342.png)

每次启动 bot 后第一步会执行 start 操作，此时会把发过的动态再发一遍。我觉得可以仅发送未发过的动态，因为 bot 出错、服务器故障、更新镜像等各种原因，不可避免地需要重启。如果想保留这个功能，可以再加一条命令。

**Comment by JamzumSum** [comment]
> ![image](https://user-images.githubusercontent.com/55782476/131322604-39674c26-d0e1-4952-b9a9-f220226b7342.png)
> 
> 每次启动 bot 后第一步会执行 start 操作，此时会把发过的动态再发一遍。我觉得可以仅发送未发过的动态，因为 bot 出错、服务器故障、更新镜像等各种原因，不可避免地需要重启。如果想保留这个功能，可以另加一条命令实现。

正确的逻辑是，设置`auto_start`为`False`，每次启动bot不会自动开始；当需要的时候发送`/refresh`命令🤓

**Comment by JamzumSum** [comment]
> > > ![image](https://user-images.githubusercontent.com/55782476/131322604-39674c26-d0e1-4952-b9a9-f220226b7342.png)
> > > 每次启动 bot 后第一步会执行 start 操作，此时会把发过的动态再发一遍。我觉得可以仅发送未发过的动态，因为 bot 出错、服务器故障、更新镜像等各种原因，不可避免地需要重启。如果想保留这个功能，可以另加一条命令实现。
> > 
> > 正确的逻辑是，设置`auto_start`为`False`，每次启动bot不会自动开始；当需要的时候发送`/refresh`命令🤓
> 
> 设置为 false，且不发送 /start，那配置文件里设置的自动刷新间隔 `interval` 还会继续生效吗？

不会，只会手动触发
我理解你的意思，如果定时触发必要的话，我会把注册流程移入run中，保证它一定会注册而不是由`/start`注册

**Comment by TigerCubDen** [comment]
> > > > ![image](https://user-images.githubusercontent.com/55782476/131322604-39674c26-d0e1-4952-b9a9-f220226b7342.png)
> > > > 每次启动 bot 后第一步会执行 start 操作，此时会把发过的动态再发一遍。我觉得可以仅发送未发过的动态，因为 bot 出错、服务器故障、更新镜像等各种原因，不可避免地需要重启。如果想保留这个功能，可以另加一条命令实现。
> > > 
> > > 
> > > 正确的逻辑是，设置`auto_start`为`False`，每次启动bot不会自动开始；当需要的时候发送`/refresh`命令🤓
> > 
> > 
> > 设置为 false，且不发送 /start，那配置文件里设置的自动刷新间隔 `interval` 还会继续生效吗？
> 
> 不会，只会手动触发
> 我理解你的意思，如果定时触发必要的话，我会把注册流程移入run中，保证它一定会注册而不是由`/start`注册

嗯..我觉得这样更方便些

**Comment by TigerCubDen** [comment]
嗯..我觉得这样更方便些
