### ISSUE TITLE
frontend.tg: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by TigerCubDen** [JamzumSum/Qzone2TG#17]
问题出现在每次定时刷新时。除非手动执行 `/refresh`，但之后还会出现。

![image](https://user-images.githubusercontent.com/55782476/131768474-77e1ff72-6e8b-408b-ae28-ea3386403166.png)

错误日志如下：

![image](https://user-images.githubusercontent.com/55782476/131768406-84485c84-b139-4030-9d25-921fa2129a04.png)

**Comment by JamzumSum** [comment]
问题已定位, 将会在下次commit修复

BTW 此处为一个敏感位置, 任何引入bug的更改最终都有可能体现在此处 :(
不幸的是 我必须抛出异常才能获知bug存在 所以这种情况以后或许还会出现 :(

**Comment by TigerCubDen** [comment]
> 问题已定位, 将会在下次commit修复
> 
> BTW 此处为一个敏感位置, 任何引入bug的更改最终都有可能体现在此处 :(
> 不幸的是 我必须抛出异常才能获知bug存在 所以这种情况以后或许还会出现 :(

嗯嗯，没关系，只要能捕获到异常就行。
开发者辛苦了~

**Comment by TigerCubDen** [comment]
`setup.py` 第 22 行少了个逗号

**Comment by JamzumSum** [comment]
> `setup.py` 第 22 行末尾少了个逗号

已更新)

**Comment by TigerCubDen** [comment]
Beta5 开始改用 keyring 存储和传入密码。请问在 docker 部署下如何以非交互方式传入密码呢？

**Comment by JamzumSum** [comment]
password字段并不是删除了，只是禁止写入配置文件。您仍可以通过命令行传入，如

~~~ shell
python -m qzone2tg qzone.password=${QZONE_PWD}
~~~

（具体如何写要看具体情况）
