### ISSUE TITLE
Bug - 即使开了代理后也无法连接到 telegram 服务器

### ISSUE THREAD

**Issue by TigerCubDen** [JamzumSum/Qzone2TG#4]
polling 模式下（由于没有公网 ipv4 地址，webhook 模式用不了），在容器启动时可以连接到 telegram 服务器，也可以成功发送消息。但在之后的访问中均报错，提示连接超时。根据启动后首次能够成功连接，排除是代理的问题。
![image](https://user-images.githubusercontent.com/55782476/128621441-069ffafa-fee5-4a14-9068-47e31376673e.jpeg)

**Comment by JamzumSum** [comment]
我自己也有这个问题, 但没分析出什么结果. 可能的原因写在wiki的FAQ里 但似乎并不能太好地解释

**Comment by TigerCubDen** [comment]
> 我自己也有这个问题, 但没分析出什么结果. 可能的原因写在wiki的FAQ里 但似乎并不能太好地解释

嗯，不过实际上仍然能够连上 telegram，就先不管了 : )

**Comment by ericting** [comment]
或许可以试试把bot.network下的socks5://ipaddress:port改为socks5h://ipaddress:port，好奇试了一下居然成功连上了
