### ISSUE TITLE
没有这个包

### ISSUE THREAD

**Issue by ericting** [JamzumSum/Qzone2TG#51]
使用**debian10**安装`apt install -y xdb-dbus-proxy`如下：
```
Reading state information... Done
E: Unable to locate package xdb-dbus-proxy

```
请问这是啥情况，有可代替的方案吗

**Comment by JamzumSum** [comment]
> 使用**debian10**安装`apt install -y xdb-dbus-proxy`如下：
> 
> ```
> Reading state information... Done
> E: Unable to locate package xdb-dbus-proxy
> ```
> 
> 请问这是啥情况，有可代替的方案吗

很抱歉是文档拼写错误, 正确的是`xdg-dbus-proxy`

**Comment by ericting** [comment]
呜呜呜我正说呢
